#!/bin/bash
export CONVERSATION_PASSWORD=$(echo "$CONVERSATION_SERVICE_CAR" | jq -r '.password')
export CONVERSATION_USERNAME=$(echo "$CONVERSATION_SERVICE_CAR" | jq -r '.username')
echo "CONVERSATION_USERNAME == $CONVERSATION_USERNAME"
echo "CONVERSATION_PASSWORD == $CONVERSATION_PASSWORD"
npm start
