#!/bin/bash
CONVERSATION_PASSWORD=$(echo "$BINDING" | jq '.password')
CONVERSATION_USERNAME=$(echo "$BINDING" | jq '.username')
echo "CONVERSATION_USERNAME == $CONVERSATION_USERNAME"
echo "CONVERSATION_PASSWORD == $CONVERSATION_PASSWORD"
npm start
